# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: purezento
  #description: description of repo
  #homepage: https://example.github.io/
  #topics: github, probot

  private: false

  has_issues: true

  has_projects: true

  has_wiki: false

  has_downloads: true

  default_branch: develop

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

branches:
  - name: develop
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ["build"]
      enforce_admins: true
      restrictions:
        required_linear_history: true
