name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:unit
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn serve --mode production
          wait-on: http://localhost:8080/
          config-file: cypress.json
          spec: "tests/e2e/**/*"
          headless: true
        env:
          CYPRESS_baseUrl: http://localhost:8080/
