name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Unit tests
        run: yarn test:unit

      - name: e2 tests
        uses: cypress-io/github-action@v1
        with:
          start: yarn serve --mode production
          wait-on: http://localhost:8080/
          config-file: cypress.json
          spec: "tests/e2e/**/*"
          headless: true
          record: true
        env:
          CYPRESS_baseUrl: http://localhost:8080/
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
